apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: collections-server
  namespace: emily
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 8087
        requestPath: /healthz
  targetRef:
    group: ""
    kind: Service
    name: collections-server
