// emily-agent/goldenbuild.go
// GoldenDocCompiler reads Tier 1 golden docs from all repos and compresses
// them into EMILY/context/full-system-context.md via claude-haiku bilingual
// Chinese/English compression (~150 tokens per source).
//
// Called each cron cycle via MaybeRebuild (only rebuilds if a source changed).
// The compiled context is prepended to emilyStaticPrompt and fed into FABLE.

package main

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// GoldenSource is one documentation file to compress into the system context.
type GoldenSource struct {
	Name   string // label in compiled output, e.g. "FATBABY"
	Path   string // absolute path
	Budget int    // max chars to read; 0 = read all
}

// GoldenDocCompiler builds EMILY/context/full-system-context.md from Tier 1 golden docs.
type GoldenDocCompiler struct {
	apiKey  string
	outPath string
	sources []GoldenSource
}

// NewGoldenDocCompiler creates a compiler with the canonical Tier 1 source list.
// emilyRoot should be the absolute path to the EMILY repo root.
func NewGoldenDocCompiler(emilyRoot, apiKey string) *GoldenDocCompiler {
	base := filepath.Dir(emilyRoot)
	return &GoldenDocCompiler{
		apiKey:  apiKey,
		outPath: filepath.Join(emilyRoot, "context", "full-system-context.md"),
		sources: []GoldenSource{
			{Name: "FATBABY", Path: filepath.Join(base, "PRRJECT_FATBABY/docs/northstar/northstar.md"), Budget: 8000},
			{Name: "FATBABY-EXEC", Path: filepath.Join(base, "PRRJECT_FATBABY/docs/northstar/executive_summary.md"), Budget: 4000},
			{Name: "EMILY-SPEC", Path: filepath.Join(base, "EMILY/emily-prime-spec.md"), Budget: 4000},
			{Name: "EMILY-BACKLOG", Path: filepath.Join(base, "EMILY/GOLDEN.md"), Budget: 0},
			{Name: "EMIREE", Path: filepath.Join(base, "EMILY/emiree-emily-fatbaby.md"), Budget: 4000},
			{Name: "RSI-ENGINE", Path: filepath.Join(base, "EMILY/docs/emily-rsi-engine-spec.md"), Budget: 0},
			{Name: "EMIREE-SPEC", Path: filepath.Join(base, "EMILY/docs/emiree-over-agent-spec.md"), Budget: 0},
			{Name: "IDUNA", Path: filepath.Join(base, "IDUNA/golden.md"), Budget: 3000},
			{Name: "APPLES", Path: filepath.Join(base, "APPLES/docs/NORTHSTAR.md"), Budget: 0},
			{Name: "MJOLNIR", Path: filepath.Join(base, "MJOLNIR/docs/NORTHSTAR.md"), Budget: 0},
			{Name: "SHANKPIT", Path: filepath.Join(base, "SHANKPIT/docs2/NORTHSTAR.md"), Budget: 4000},
			{Name: "EMILYOS", Path: filepath.Join(base, "EmilyOS/docs/NORTHSTAR.md"), Budget: 0},
			{Name: "PITVIPER", Path: filepath.Join(base, "PITVIPER/docs/NORTHSTAR.md"), Budget: 0},
			{Name: "EMILY-CLI", Path: filepath.Join(base, "emily.cli/docs/NORTHSTAR.md"), Budget: 0},
			{Name: "GTM", Path: filepath.Join(base, "PRRJECT_FATBABY/docs/GTM_FUNNEL.md"), Budget: 3000},
			{Name: "TRAINING", Path: filepath.Join(base, "EMILY/docs/TRAINING_PIPELINE.md"), Budget: 2000},
		},
	}
}

// MaybeRebuild rebuilds the full context if any source is newer than the output,
// or if the output does not exist. Safe to call every cron cycle.
func (g *GoldenDocCompiler) MaybeRebuild(ctx context.Context) error {
	outStat, err := os.Stat(g.outPath)
	needBuild := os.IsNotExist(err)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("stat output: %w", err)
	}
	if !needBuild {
		for _, src := range g.sources {
			stat, serr := os.Stat(src.Path)
			if serr != nil {
				continue
			}
			if stat.ModTime().After(outStat.ModTime()) {
				log.Printf("goldenbuild: %s updated, rebuilding full-system-context.md", src.Name)
				needBuild = true
				break
			}
		}
	}
	if !needBuild {
		return nil
	}
	return g.Build(ctx)
}

// Build reads all sources, compresses each via haiku, and writes full-system-context.md.
func (g *GoldenDocCompiler) Build(ctx context.Context) error {
	var sections []string
	built := 0
	for _, src := range g.sources {
		raw, err := os.ReadFile(src.Path)
		if err != nil {
			log.Printf("goldenbuild: skip %s: %v", src.Name, err)
			continue
		}
		text := string(raw)
		if src.Budget > 0 && len(text) > src.Budget {
			text = text[:src.Budget]
		}
		compressed, err := g.compress(ctx, src.Name, text)
		if err != nil {
			log.Printf("goldenbuild: compress %s failed (%v), using truncated fallback", src.Name, err)
			if len(text) > 500 {
				text = text[:500]
			}
			compressed = fmt.Sprintf("## %s\n%s\n", src.Name, text)
		}
		sections = append(sections, compressed)
		built++
	}

	var b strings.Builder
	b.WriteString(fmt.Sprintf("# 全系統上下文 FULL SYSTEM CONTEXT — %s\n", time.Now().UTC().Format("2006-01-02")))
	b.WriteString("*Auto-generated by GoldenDocCompiler. Dense bilingual context for Emily Prime.*\n")
	b.WriteString(fmt.Sprintf("*Sources compiled: %d/%d.*\n\n", built, len(g.sources)))
	for _, s := range sections {
		b.WriteString(s)
		b.WriteString("\n")
	}

	if err := os.MkdirAll(filepath.Dir(g.outPath), 0o755); err != nil {
		return fmt.Errorf("mkdir context/: %w", err)
	}
	if err := os.WriteFile(g.outPath, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("write full-system-context.md: %w", err)
	}
	log.Printf("goldenbuild: wrote %s (%d bytes, %d/%d sources)", g.outPath, b.Len(), built, len(g.sources))
	return nil
}

// compress calls claude-haiku to compress doc into a dense bilingual ≤180 token section.
func (g *GoldenDocCompiler) compress(ctx context.Context, name, text string) (string, error) {
	if g.apiKey == "" {
		return fmt.Sprintf("## %s\n(no ANTHROPIC_API_KEY — raw context unavailable)\n", name), nil
	}

	system := `You are Emily Prime's context compressor for EINHORN_INDUSTRIAL.
Compress documentation into a dense ≤180 token bilingual section.
Rules:
- Chinese for concepts/state (系統/北極星/完成/待辦/架構/待實現), English for technical names/APIs/file paths
- Every token carries signal — no filler, no repetition, no preamble
- Preserve: purpose, current status, open blockers, key interfaces/endpoints/paths
- Start with ## NAME (use the exact label provided)
- Output ONLY the compressed section`

	user := fmt.Sprintf("Label: %s\n\nDoc:\n%s", name, text)

	body := map[string]any{
		"model":      "claude-haiku-4-5-20251001",
		"max_tokens": 400,
		"system":     system,
		"messages":   []map[string]any{{"role": "user", "content": user}},
	}
	payload, _ := json.Marshal(body)

	req, err := http.NewRequestWithContext(ctx, "POST",
		"https://api.anthropic.com/v1/messages", bytes.NewReader(payload))
	if err != nil {
		return "", err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("x-api-key", g.apiKey)
	req.Header.Set("anthropic-version", "2023-06-01")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	raw, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != 200 {
		return "", fmt.Errorf("api %d: %s", resp.StatusCode, raw)
	}

	var result struct {
		Content []struct {
			Type string `json:"type"`
			Text string `json:"text"`
		} `json:"content"`
	}
	if err := json.Unmarshal(raw, &result); err != nil {
		return "", fmt.Errorf("parse response: %w", err)
	}
	for _, block := range result.Content {
		if block.Type == "text" {
			return strings.TrimSpace(block.Text) + "\n", nil
		}
	}
	return "", fmt.Errorf("no text block in haiku response")
}
